New iban transfer
snabble/Android-SDK pull request #13
Opened 2021-12-07 13:38 UTC by ajungg

2021-12-09 08:53 UTC, rekire requested changes

2021-12-09 08:53 UTC, rekire commented on ui/src/main/java/io/snabble/sdk/ui/payment/SEPACardInputView.java
> +
Here are so many changes, why not converting it to kotlin?

2021-12-09 08:53 UTC, rekire commented on core/src/main/java/io/snabble/sdk/PaymentOriginCandidateHelper.java
> +                        if (response.code() == 201) {
I would check for 2xx there could be also a success method which you can use

2021-12-09 11:13 UTC, ajungg commented on ui/src/main/java/io/snabble/sdk/ui/checkout/PaymentStatusView.kt
> +        startPollingForPaymentOriginCandidate()
No because the view-lifecycle can be different from the activity-lifecycle (think one activity based app with multiple fragments)

2021-12-09 11:14 UTC, ajungg commented on core/src/main/java/io/snabble/sdk/PaymentOriginCandidateHelper.java
> +                        if (response.code() == 201) {
That would break the implementation. A 200 is a successful request but a 201 indicated that a resource was created, which is what iam waiting for here

2021-12-09 11:17 UTC, ajungg commented on ui/src/main/java/io/snabble/sdk/ui/payment/SEPACardInputView.java
> +
Changes creeped up, did not think of converting it fully at the time

2021-12-10 07:02 UTC, rekire commented
LGTM, but I cannot verify it

2021-12-14 12:09 UTC, merged