Activity API + RoutingTargets
snabble/Android-SDK pull request #16
Opened 2022-01-17 14:19 UTC by ajungg

2022-01-18 12:43 UTC, rekire requested changes
I still need to test everything on the device, but this looks very solid.

2022-01-18 12:43 UTC, rekire commented on ui/src/main/java/io/snabble/sdk/ui/payment/PaymentOptionsFragment.kt
> +
Useless code

2022-01-18 12:43 UTC, rekire commented on ui/src/main/java/io/snabble/sdk/ui/payment/Payone.kt
> +            project.events.logError("Payone Error: No tokenization url")
Good catch!

2022-01-18 12:43 UTC, rekire commented on ui/src/main/java/io/snabble/sdk/ui/payment/ProjectPaymentOptionsActivity.kt
> +        const val ARG_BRAND = ProjectPaymentOptionsView.ARG_BRAND
Don't we need the `@JvmStatic` for all those kind of constants for Java compatibility?

2022-01-18 12:43 UTC, rekire commented on ui/src/main/java/io/snabble/sdk/ui/search/SearchHelper.kt
> +}
Might be a better idea to move this to the SnabbleUI class to eliminate this singleton.

2022-01-18 12:43 UTC, rekire commented on ui/src/main/res/layout/snabble_item_searchable_product.xml
> +    android:minHeight="48dp"
Can you explain this change?

2022-01-19 15:24 UTC, ajungg commented on ui/src/main/res/layout/snabble_item_searchable_product.xml
> +    android:minHeight="48dp"
Bothered me, search entries were uneven when no barcodes were present

2022-01-19 15:26 UTC, ajungg commented on ui/src/main/java/io/snabble/sdk/ui/payment/ProjectPaymentOptionsActivity.kt
> +        const val ARG_BRAND = ProjectPaymentOptionsView.ARG_BRAND
const vals are already inplicit jvm static

2022-01-24 08:33 UTC, rekire requested changes
In the Aldi Project I see with an empty cart the payment selector.

2022-01-26 09:31 UTC, merged