Add address and email to payone form
snabble/Android-SDK pull request #167
Opened 2024-01-23 16:42 UTC by cmaier

- Add input fields for address and email to form
- WIP: Integration of new address fields
- UI fixes and adjustments
- Fix string refs
- Add address and email to encryptedOrigin

### How to test?

### Definition of Done

- [ ] Changelog gepflegt
- [ ] Dokumentation gepflegt
- [ ] Alle Anforderung des Issues sind erfüllt
- [ ] Selbst greviewed _(aka [Self-Reviews (eng)](https://www.nerdwallet.com/blog/engineering/why-you-should-be-doing-self-reviews/))_
- [ ] Review mit Product Owner _(Release-Variante o. Minified Build)_

#### App Tests
- [ ] Minified getestet? _(aka. Release Build)_
- [ ] Environements beachtet _(Production/Staging)_
- [ ] Unterstützte Sprachen sind getestet
- [ ] Light-/Dark-Mode getestet
- [ ] Edge-Cases getestet
- [ ] Android API Levels wurden berücksichtigt _(minSdk?)_

#### Testing
- [ ] Tests geschrieben _(aka Unit-Tests, Integration-Tests)_
- [ ] Tests lokal laufen gelassen

2024-01-25 11:08 UTC, Fabtron requested changes
Works fine, just one small suggestion.

2024-01-25 11:08 UTC, Fabtron commented on ui/src/main/java/io/snabble/sdk/ui/payment/PayoneInputView.kt
> +                name = requireNotNull(name),
If some of these values magically happens to be null the user is stuck in the ui without any feedback until he navigates back. Shouldn't we provide information that something went wrong or at least wrap it up with a try an catch block launching `fail()` with a reason?

2024-01-25 11:25 UTC, cmaier commented on ui/src/main/java/io/snabble/sdk/ui/payment/PayoneInputView.kt
> +                name = requireNotNull(name),
To be honest, it's been like this before. I acutally dislike using `requireNotNull()` at all. I just left it, as it is. Seems to work.

2024-01-26 07:54 UTC, cmaier commented on ui/src/main/java/io/snabble/sdk/ui/payment/PayoneInputView.kt
> +                name = requireNotNull(name),
> So just because it was like this before, we shouldn't change it? 🤔
Did I make this statement? What is your intention and goal?

> Its not working it's just doesn't crash 🙃
Can provide an implementation and how to test it? I didn't dive that deep into this Javascript implementation and Payone.

2024-01-26 11:00 UTC, Fabtron commented on ui/src/main/java/io/snabble/sdk/ui/payment/PayoneInputView.kt
> +                name = requireNotNull(name),
Yes,it was ur statement, to improve code as we can. I already suggested to wrap it in a try catch block so that we can inform the the user as done in `fail` or over the same way to make some toast appear. There is not much to dive in. 
If u don't see any additional value in these changes, u can merge this PR cause the mandatory features are working. 
Its up to u

2024-01-26 11:00 UTC, Fabtron approved these changes

2024-01-26 12:10 UTC, cmaier commented on ui/src/main/java/io/snabble/sdk/ui/payment/PayoneInputView.kt
> +                name = requireNotNull(name),
I figured it out myself and tested it. In the case that Payone says the data is valid but something we need is
still missing, we will fail the process and inform the user. I've added a plain generic english only fail info.

Does this work for you?

2024-01-26 12:31 UTC, Fabtron commented on ui/src/main/java/io/snabble/sdk/ui/payment/PayoneInputView.kt
> +                name = requireNotNull(name),
Yes, that looks fine. Thank u !

2024-01-26 15:27 UTC, merged