APPS-55 Persist used project + improve initialization and view behavior
snabble/Android-SDK pull request #18
Opened 2022-02-11 15:25 UTC by ajungg

2022-02-14 10:32 UTC, rekire requested changes

2022-02-14 10:32 UTC, rekire commented on core/src/main/java/io/snabble/sdk/UserPreferences.kt
> +    interface OnNewAppUserListener {
no fun interface?

2022-02-14 10:32 UTC, rekire commented on core/src/main/java/io/snabble/sdk/payment/PaymentCredentialsStore.java
> +        Logger.errorEvent("Removing payment credentials, because key store id differs");
Please verify that this change is intended

2022-02-14 10:32 UTC, rekire commented on java-sample/src/main/java/io/snabble/testapp/App.java
>          snabble.setup(this, config, new Snabble.SetupCompletionListener() {
When the listener is not used here why is this then required?

2022-02-14 10:32 UTC, rekire commented on ui/src/main/java/io/snabble/sdk/ui/BaseFragment.kt
> +                InitializationState.INITIALIZING -> {
I would comma separate the states here, the blocks are equal

2022-02-14 10:32 UTC, rekire commented on ui/src/main/java/io/snabble/sdk/ui/BaseFragment.kt
> +    abstract fun onCreateViewInternal(
Internal? What is about: `onCreateActualView`?

2022-02-14 10:32 UTC, rekire commented on ui/src/main/java/io/snabble/sdk/ui/BaseFragment.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
I think we should add the `@CallSuper` annotation or add the method `onActualViewCreated` I think this way is a bit dangerous or better add a `sealed` keyword to avoid overriding this method

2022-02-14 10:32 UTC, rekire commented on ui/build.gradle
> +        disable 'LabelFor', 'ContentDescription', 'MissingTranslation'
Please remove `'ContentDescription'` and fix the warnings

2022-02-14 10:32 UTC, rekire commented on ui/src/main/java/io/snabble/sdk/ui/checkout/CheckoutActivity.kt
> +                else -> {}
Please list the cases just for the case that this changes in the future

2022-02-14 10:32 UTC, rekire commented on ui/src/main/java/io/snabble/sdk/ui/checkout/CheckoutPOSFragment.kt
> +open class CheckoutPOSFragment : BaseFragment() {
Since we have here now this abstract base class and we have here just now only boilerplate code we can add an optional constructor parameter to return the layout id to inflate. There are multiple of this boilerplate classes

So this class would be:
```kotlin
open class CheckoutPOSFragment : BaseFragment(R.layout.snabble_fragment_checkout_pos)
```

2022-02-14 10:32 UTC, rekire commented on ui/src/main/java/io/snabble/sdk/ui/payment/Payone.kt
> +        val href: String
Are you sure?

2022-02-14 10:32 UTC, rekire commented on ui/src/main/java/io/snabble/sdk/ui/BaseFragment.kt
> +    override fun onCreateView(
Might be a `sealed` keyword might be not bad to avoid overriding this method

2022-02-16 10:17 UTC, ajungg commented on core/src/main/java/io/snabble/sdk/Snabble.kt
> +        projects = Collections.unmodifiableList(newProjects)
I would like to keep them, because just using List one can cast it to MutableList and modify it that way

2022-02-18 06:50 UTC, rekire approved these changes

2022-02-21 14:20 UTC, merged