Apps 1642 add scanner support for invalid drv and other items
snabble/Android-SDK pull request #232
Opened 2024-12-23 08:35 UTC by Fabtron

APPS-

### How to test?

### Definition of Done

- [ ] Issue is linked
- [ ] All requirements of the issue are fulfilled
- [ ] Changelog is updated
- [ ] Documentation is updated
- [ ] [Self-Review](https://www.nerdwallet.com/blog/engineering/why-you-should-be-doing-self-reviews/)
- [ ] Review with the Product Owner _(Release-Variante o. Minified Build)_

#### App Tests
- [ ] Minified build has been tested _(aka. Release Build)_
- [ ] Environments have been taken care of _(Production/Staging)_
- [ ] Supported languages have been tested
- [ ] Light-/Dark-Mode has been tested
- [ ] Edge-Cases have been tested
- [ ] Android API Levels have been taken care of _(minSdk?)_

#### Testing
- [ ] Tests have been written _(aka Unit-Tests, Integration-Tests, ...)_

2025-01-06 15:18 UTC, cmaier requested changes

2025-01-06 15:18 UTC, cmaier commented on core/src/main/java/io/snabble/sdk/shoppingcart/ShoppingCart.kt
> +        }
Cannot be null!?

2025-01-06 15:18 UTC, cmaier commented on core/src/main/java/io/snabble/sdk/shoppingcart/ShoppingCartUpdater.kt
> +                        onInvalidItemsDetectedListener?.let { it(itemIds) }
`onInvalidItemsDetectedListener?.invoke(itemIds)` is easier to read!

2025-01-06 15:18 UTC, cmaier commented on core/src/main/java/io/snabble/sdk/shoppingcart/ShoppingCart.kt
> +            onInvalidItemsDetectedListener?.let { it(items) }
`onInvalidItemsDetectedListener?.invoke(items)` is easier to read!

2025-01-07 06:56 UTC, Fabtron commented on core/src/main/java/io/snabble/sdk/shoppingcart/ShoppingCartUpdater.kt
> +                        onInvalidItemsDetectedListener?.let { it(itemIds) }
true, changed :D

2025-01-07 10:40 UTC, cmaier approved these changes

2025-01-07 13:21 UTC, merged