Add deposit return voucher states as part of the checkout process (Apps-2040)
snabble/Android-SDK pull request #233
Opened 2024-12-27 09:00 UTC by Fabtron

### What's new?

We can now track the state of deposit return vouchers in the checkout process. If a redemption failes, due to whatever reason, we receive a matching state. The state is handled and the user is informed via a Dialog that the reffering deposit return voucher will be removed to proceed with the checkout, e.g. to try again without it.

APPS-2040

### How to test?
Integrate this branch into an app using drv's and scan the product linked in the issue. Add an additional item to get to a positive amount and checkout. -> The dialog should pop up after the checkout failed.

### Definition of Done

- [ ] Issue is linked
- [ ] All requirements of the issue are fulfilled
- [ ] Changelog is updated
- [ ] Documentation is updated
- [ ] [Self-Review](https://www.nerdwallet.com/blog/engineering/why-you-should-be-doing-self-reviews/)
- [ ] Review with the Product Owner _(Release-Variante o. Minified Build)_

#### App Tests
- [ ] Minified build has been tested _(aka. Release Build)_
- [ ] Environments have been taken care of _(Production/Staging)_
- [ ] Supported languages have been tested
- [ ] Light-/Dark-Mode has been tested
- [ ] Edge-Cases have been tested
- [ ] Android API Levels have been taken care of _(minSdk?)_

#### Testing
- [ ] Tests have been written _(aka Unit-Tests, Integration-Tests, ...)_

2025-01-06 15:37 UTC, cmaier requested changes
Works fine. Just minor findings.

2025-01-06 15:37 UTC, cmaier commented on core/src/main/java/io/snabble/sdk/checkout/CheckoutApi.kt
> +    @SerializedName("rolledback")
Is the is correct that it's all lower case and not camel case?

2025-01-06 15:37 UTC, cmaier commented on core/src/main/java/io/snabble/sdk/checkout/CheckoutApi.kt
> +    val depositReturnVouchers: List<DepositReturnVoucher>? = null,
The annotation is obsolete in this case, but I don't mind, we can keep it!

2025-01-06 15:37 UTC, cmaier commented on ui/src/main/java/io/snabble/sdk/ui/cart/CheckoutBar.kt
> +            }
This could lead to "null" being appended. Maybe this `cart.getByItemId(it.refersTo)?.displayName ?: ""` would be more appropriate or even this:

```kotlin
.mapNotNull { cart.getByItemId(it.refersTo)?.displayName }
.jointToString(/* ... */)
```

2025-01-07 07:01 UTC, Fabtron commented on core/src/main/java/io/snabble/sdk/checkout/CheckoutApi.kt
> +    @SerializedName("rolledback")
yes it is correct

2025-01-07 07:04 UTC, Fabtron commented on ui/src/main/java/io/snabble/sdk/ui/cart/CheckoutBar.kt
> +            }
I like the second approach. Goood point changed it 👍

2025-01-07 07:10 UTC, Fabtron commented on core/src/main/java/io/snabble/sdk/checkout/CheckoutApi.kt
> +    val depositReturnVouchers: List<DepositReturnVoucher>? = null,
👍

2025-01-07 09:49 UTC, cmaier approved these changes

2025-01-07 16:15 UTC, merged