Gradle plugin
snabble/Android-SDK pull request #48
Opened 2022-06-14 15:28 UTC by rekire

Here is the first version of the gradle plugin. you need to publish it to your local maven repo in order to test it.

```shell
./gradlew :gP:pTML
```

If it is yelling around that the plugin is unknown comment out the id and the snabble dsl. after the first execution of the command above it should work without out commenting it. This is basically just because it is not yet published.

2022-06-14 15:31 UTC, rekire commented
The huge changelog is caused by the stupid suggestion of AS to rebase the branch
the documentation changes are not yet done

2022-06-15 11:16 UTC, ajungg requested changes
Changes to Config.kt and BuildEnvironment.kt are both ignored and the persisted value is used, even if no value was specified in the applications build.gradle

Also the sample app currently crashes on fresh installs,

2022-06-15 11:16 UTC, ajungg commented on core/src/main/java/io/snabble/sdk/SnabbleInitializer.kt
> +        fun Environment.capitalizedName() = Character.toUpperCase(name[0]) + name.substring(1).lowercase()
Should be moved to Environment class

2022-06-15 11:16 UTC, ajungg commented on core/src/main/java/io/snabble/sdk/SnabbleInitializer.kt
> +        fun Properties.getBoolean(key: String, default: Boolean) =
PropertiesUtils.kt ?

2022-06-15 11:16 UTC, ajungg commented on gradle-plugin/src/main/kotlin/io/snabble/setup/BuildEnvironment.kt
> +open class BuildEnvironment(private val environment: Environment) {
Is there a way to Avoid the duplicatin of the config file?

2022-06-22 04:58 UTC, merged