[WIP] New UI toolkit
snabble/Android-SDK pull request #58
Opened 2022-08-24 11:26 UTC by rekire

Features:
- Onboarding (in new Modul UI-Tooklit)
- Accessibility-Toolkit extracted

2022-09-06 10:25 UTC, cmaier requested changes
I found a few things but I believe not all of them can or must be addressed.

2022-09-07 05:27 UTC, rekire commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/onboarding/terms/RawHtmlFragment.kt
> +            @Deprecated("Legacy code for Android 5 & 6")
To be honest there is nothing to be replaced. This is just legacy support: On that target platforms this method was not deprecated and there is no alternative.

2022-09-07 05:28 UTC, rekire commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/utils/LinkClickListener.kt
> +            val b = Selection.getSelectionEnd(buffer)
maybe start and end :-D

2022-09-07 05:39 UTC, cmaier commented on kotlin-customization-sample/src/main/res/navigation/mobile_navigation.xml
> +    </fragment>
kotlin-customization-sample is not relevant here, ca be ignored.

2022-09-07 05:41 UTC, cmaier commented on kotlin-sample/src/main/java/io/snabble/sdk/sample/MainActivity.kt
>  package io.snabble.sdk.sample
kotlin-customization-sample is not relevant here, ca be ignored.

2022-09-07 05:43 UTC, cmaier commented on kotlin-sample/src/main/res/navigation/mobile_navigation.xml
> +    </fragment>
Does not apply for the OnboardingActivity but for the MainActivity if used there.

2022-09-07 06:05 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/SnabbleUiToolkit.kt
> +                    val deeplink = Uri.parse(requireNotNull(args?.getString(DEEPLINK)))
It's intended to crash so that it can be fixed easily.

2022-09-07 06:20 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/onboarding/terms/LegalFragment.kt
> +        resources.openRawResource(requireNotNull(arguments?.getInt(resId))).bufferedReader()
Long story short; it's intended to crash.

2022-09-07 09:14 UTC, cmaier commented on kotlin-customization-sample/src/main/java/io/snabble/sdk/customization/MainActivity.kt
> +        navController.addOnDestinationChangedListener { _, destination, arguments ->
Done

2022-09-07 09:31 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/SnabbleUiToolkit.kt
> +        val cb = actions[event]
Done

2022-09-07 09:32 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/SnabbleUiToolkit.kt
> +        }
Done

2022-09-07 09:32 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/SnabbleUiToolkit.kt
> +    fun getHostFragmentActivity(context: Context?): FragmentActivity? {
Done.

2022-09-07 10:21 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/onboarding/OnboardingFragment.kt
> +        val model = arguments?.getParcelable<OnboardingModel>("model") ?: throw IllegalArgumentException()
Done

2022-09-07 10:21 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/onboarding/OnboardingFragment.kt
> +        val v: View = inflater.inflate(R.layout.snabble_fragment_onboarding, container, false)
Done.

2022-09-07 10:22 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/onboarding/OnboardingFragment.kt
> +    }
Just moved out of the class :v:

2022-09-07 10:40 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/onboarding/OnboardingStepView.kt
> +        } ?: run { termsButton.isVisible = false }
Done.

2022-09-07 10:41 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/onboarding/OnboardingStepView.kt
> +        }
Done.

2022-09-07 10:41 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/onboarding/OnboardingFragment.kt
> +        val model = arguments?.getParcelable<OnboardingModel>("model") ?: throw IllegalArgumentException()
Done.

2022-09-07 10:47 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/onboarding/terms/RawHtmlFragment.kt
> +            @Deprecated("Legacy code for Android 5 & 6")
Removed the warning by added a ReplaceWith w/ an empty string.

2022-09-07 10:47 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/onboarding/terms/RawHtmlFragment.kt
> +        } catch (e: Exception) {}
Done.

2022-09-07 10:56 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/utils/LinkClickListener.kt
> +            val b = Selection.getSelectionEnd(buffer)
Renamed. 👍

2022-09-07 10:56 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/utils/LinkClickListener.kt
> +            val off = widget.layout.getOffsetForHorizontal(line, x.toFloat())
Renamed to offset.

2022-09-08 09:22 UTC, cmaier commented on kotlin-customization-sample/src/main/java/io/snabble/sdk/customization/MainActivity.kt
> +            val json = resources.assets.open("onboardingConfig.json").bufferedReader().readText()
Done, for now.

2022-09-08 09:22 UTC, cmaier commented on ui-toolkit/src/main/kotlin/io/snabble/sdk/utils/LinkClickListener.kt
> +            val selEnd = max(a, b)
Done.

2022-09-08 09:23 UTC, cmaier approved these changes

2022-09-09 04:44 UTC, merged